name: zerodce_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0
  - python=3.7
  - pytorch>=1.7.0
  - dominate=2.4.0
  - matplotlib=3.3.4
  - numpy=1.19.2
  - opencv=3.4.2
  - pillow=8.1.2
  - pip=21.0.1
  - pip3:
    - cmake==3.18.4
    - build-essential
    - dlib==19.22.0
    - docopt==0.6.2
    - face-recognition==1.3.0
    - imutils==0.5.4
    - ssim-pil==1.0.12
    - streamlit==0.80.0
